version: '3'

services:  

  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: node app/app.js
    volumes:
      - D:\M1\S2\foot\FootballGame-ML\logsGames:/foot/logsGames
      # - D:\M1\S2\foot\FootballGame-ML\app\database.db:/foot/app/database.db
    ports:
      - "3000:3000"
    links:
      - rabbit
      - worker
    depends_on:
      - rabbit
      - worker
      
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./run_celery.sh
    volumes:
      - D:\M1\S2\foot\FootballGame-ML\logsGames:/foot/logsGames
    links:
      - rabbit
    depends_on:
      - rabbit
